### PR TITLE
Update package.json to fix reference to just .NET Runtime

### PR DESCRIPTION
**Pull request by baronfel**

### CODE REVIEW

**Review by nagilson — APPROVED** [review]
LGTM, good catch

**Comment by nagilson** [comment]
Somehow your description change broke all of vscode
'Failed to get VS Code archive location
Failed to run tests
'

**Comment by nagilson** [comment]
jk (sorta)

**Comment by baronfel** [comment]
The windows test failures are absolutely baffling.

**Comment by nagilson** [comment]
Probably the vscode team broke something over the past hour between your pr and my pr, ive seen this happen once before a long time ago on a different machine....

Its possible I broke something but I doubt it. Lets try again and see if theyve fixed it

**Comment by nagilson** [comment]
this was failing due to dropped 32 bit support

**Pull request merged**
