### PR TITLE
Adding acquireStatus command to runtime extension

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/vscode-dotnet-runtime/issues/331

### CODE REVIEW

**Review by NTaylorMullen — APPROVED** [review]
Looks great! I'm a bit hesitant about adding it also to the SDK side but it's minimal work so why not? 😆

**Comment by sfoslund** [comment]
> I'm a bit hesitant about adding it also to the SDK side but it's minimal work so why not?

This command already exists on the SDK side, I'm adding it to the runtime extension since we've had some users requesting it.

**Comment by josetr** [comment]
Thanks for the quick fix. Any idea when this update will be available in the marketplace?

**Comment by sfoslund** [comment]
I'll release a new version at some point this week, probably tomorrow. I'll ping here when it's released.

**Comment by sfoslund** [comment]
Version 1.4.0 has been released, please let us know if you have any problems, thanks!

**Comment by gulbanana** [comment]
I'm not sure the change is working as intended. I debugged the new release, and found that in `DotnetCoreAcquisitionWorker.acquireStatus`, execution reaches this line: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/vscode-dotnet-runtime-library/src/Acquisition/DotnetCoreAcquisitionWorker.ts#L78
```
        if (installedVersions.includes(version) && fs.existsSync(dotnetPath)) 
```

At this point, `dotnetPath` has been calculated correctly and `fs.existsSync(dotnetPath)` returns `true`, but `installedVersions` is an empty array, so the function returns undefined. It looks like installedVersions gets set by `acquireCore()` - so you'd have to call dotnet.acquire before dotnet.acquireStatus, which defeats the purpose?

**Comment by sfoslund** [comment]
> installedVersions is an empty array, so the function returns undefined. It looks like installedVersions gets set by acquireCore() - so you'd have to call dotnet.acquire before dotnet.acquireStatus, which seems to defeat the purpose.

installedVersions in this context is saved as part of the extension state, so it's persistent even when the extension shuts down/ starts up. Do you have a repro where the new command is behaving unexpectedly?

**Comment by josetr** [comment]
@sfoslund I can confirm that @gulbanana is right. `acquireStatus` only works after calling the `acquire` command. In the following example, the first `dotnetPath not found` message is shown every time you start vscode and the message `dotnetPath still not found` is never shown.

```ts
let commandResult = await vscode.commands.executeCommand('dotnet.acquireStatus', { version: version, requestingExtensionId });
if (!commandResult?.dotnetPath) {
    vscode.window.showInformationMessage("dotnetPath not found");

    commandResult = await vscode.commands.executeCommand('dotnet.acquire', { version: version, requestingExtensionId });
    if (!commandResult?.dotnetPath;)
        throw new Error('Could not resolve dotnet path!');

    commandResult = await vscode.commands.executeCommand('dotnet.acquireStatus', { version: version, requestingExtensionId });
    if (!commandResult?.dotnetPath)
        vscode.window.showInformationMessage("dotnetPath still not found!");
}
```

**Comment by gulbanana** [comment]
i didn't get time to put together a repro yet, sorry, but @josetr's code produces the same result for me. i do see that installedVersions should be coming from state... i wonder why it's empty

**Comment by sfoslund** [comment]
> i do see that installedVersions should be coming from state... i wonder why it's empty

I'm wondering the same thing. Investigating this is on my backlog, I hope to get to it some time this week, sorry for the delay.

**Comment by sfoslund** [comment]
Just released a new version (1.5.0) with this issue fixed, thanks for pointing it out!

**Pull request merged**
