### PR TITLE
🦅 Enable TSA Per Requirement ✈️

### PR DESCRIPTION
**Pull request by nagilson**
TSA Upload is a new standard and requirement per Microsoft policy to add additional code checks.

### CODE REVIEW

**Comment by nagilson** [comment]
You can see that it passed here https://dev.azure.com/dnceng/internal/_build/results?buildId=2551454&view=logs&j=bc38e8b8-e027-53cb-48e7-2adbd1070eca&t=246679db-85e5-5489-6690-2e1191fab1c0 and in our email.

**Review by joeloff — APPROVED** [review]

**Review by MiYanni — APPROVED** [review]

**Comment by jmaa4** [comment]
https://github.com/dotnet/vscode-dotnet-runtime/pull/1975#issue-2562823720

**Comment by jmaa4** [comment]
a

**Comment by jmaa4** [comment]
https://github.com/dotnet/vscode-dotnet-runtime/pull/1975#issue-2562823720

**Pull request merged**
