### PR TITLE
Normalize install scripts line endings

### LINKED ISSUE #129: Error loading the ARM file
The issue text was copied to the clipboard.  Please paste it into this window.

**Repro steps:**

1.Open WSL (Ubuntu 20.04)
2. Navigate to the git repo directory
3. code .
4. Open azuredeploy.json file
[DotNetAcquisition1601910487969.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5328237/DotNetAcquisition1601910487969.txt)

**Extension Version:** 0.1.2
**Error Message:** Dotnet Core Acquisition Failed: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.8" -Runtime dotnet -Version 3.1.8
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 5: 
: not found
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

**Error Stack:** Error: Dotnet Core Acquisition Failed: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.8" -Runtime dotnet -Version 3.1.8
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 5: 
: not found
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/extension.js:211:111243

### PR DESCRIPTION
**Pull request by sfoslund**
Manually verified that this fixes #129

### CODE REVIEW

**Review by NTaylorMullen — APPROVED** [review]

**Review by wli3 — APPROVED** [review]

**Comment by anthony-c-martin** [comment]
@sfoslund - would it be possible to generate a release to pick up this fix? We've noticed this occurs when using VSCode with WSL remoting.

**Comment by sfoslund** [comment]
Yes, we just merged branding updates for version 0.2.0 and should be releasing that version soon.

**Comment by sfoslund** [comment]
Version 0.2.0 was just released, please try it out and let us know if you see any further issues- thanks!

**Comment by lr90** [comment]
Sorry guys, still hitting issues with 0.2.0 ?

``` .NET Runtime
Downloading .NET runtime version(s) 3.1.10 ... Error!
Failed to download .NET runtime 3.1.10:
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:25 char:3
+ if [ -t 1 ] && command -v tput > /dev/null; then
+   ~
Missing '(' after 'if' in if statement.
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:25 char:5
+ if [ -t 1 ] && command -v tput > /dev/null; then
+     ~
Missing type name after '['.
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:25 char:13
+ if [ -t 1 ] && command -v tput > /dev/null; then
+             ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:28 char:7
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+       ~
Missing '(' after 'if' in if statement.
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:28 char:9
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+         ~
Missing type name after '['.
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:28 char:26
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                          ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:28 char:30
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                              ~
Missing type name after '['.
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:42 char:13
+ say_warning() {
+             ~
An expression was expected after '('.
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:46 char:9
+ say_err() {
+         ~
An expression was expected after '('.
At C:\Users\username\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.2.0\dist\install 
scripts\dotnet-install.ps1:47 char:67
+     printf "%b\n" "${red:-}dotnet_install: Error: $1${normal:-}" >&2
+                                                                   ~
Missing file specification after redirection operator.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 


 Error!
.NET Acquisition Failed: undefined

```

**Comment by lr90** [comment]
Hm, OK closing and reopened VSCode and this time it worked (in Windows)!

```
Downloading .NET runtime version(s) 3.1.10 .................. Done!
.NET 3.1.10 executable path: c:\Users\username\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\3.1.10\dotnet.exe
```

However when it attempts to load under WSL: Ubuntu I'm still getting this error:
```
Downloading .NET runtime version(s) 3.1.10 ... Error!
Failed to download .NET runtime 3.1.10:
Command failed: "/home/username/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/username/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.10" -Runtime dotnet -Version 3.1.10
/home/username/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.2.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected


 Error!
.NET Acquisition Failed: Command failed: "/home/username/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.2.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/username/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.10" -Runtime dotnet -Version 3.1.10
/home/username/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.2.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

```

**Comment by sfoslund** [comment]
@lr90 thanks for the report! The scripts are cached so it is likely that you'll have to run the extension once or twice to get the fix once the extension has been updated. Is the WSL issue happening repeatedly?

**Comment by lr90** [comment]
vscode-dotnet-runtime-0.2.0 seems fine (with restarts) in both Windows + WSL. I still have an issue with the Bicep extension under WSL but I'll hold fire until 0.2 is released and then revisit it. Thanks :-)

**Pull request merged**
